##################################################################################
# Common
##################################################################################

project_name: 'decision sabotage'
group_name: 'test'
exp_name: 'base'
seed: 0
server: 'local'
